apiVersion: v1
kind: PersistentVolume
metadata:
  name: book-notes-postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: book-notes
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: book-notes-local
  hostPath:
    path: /var/lib/book-notes/postgres
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - books-dev-k8s-worker
