apiVersion: v1
kind: ConfigMap
metadata:
  name: book-notes-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "book-notes.commonLabels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.app.config.nodeEnv | quote }}
  PORT: {{ .Values.app.port | quote }}
  DATABASE_HOST: {{ .Values.app.config.databaseHost | quote }}
  DATABASE_PORT: {{ .Values.app.config.databasePort | quote }}
  DATABASE_NAME: {{ .Values.app.config.databaseName | quote }}
  DATABASE_USER: {{ .Values.app.config.databaseUser | quote }}
  DATABASE_SSL: {{ .Values.app.config.databaseSsl | quote }}
