apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-notes
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "book-notes.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: book-notes
spec:
  replicas: {{ .Values.app.replicaCount }}
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "book-notes.appSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "book-notes.appSelectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        {{- toYaml .Values.app.nodeSelector | nindent 8 }}
      terminationGracePeriodSeconds: 20
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: book-notes
          image: {{ printf "%s:%s" .Values.app.image.repository .Values.app.image.tag | quote }}
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
          envFrom:
            - configMapRef:
                name: book-notes-config
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.existingDatabaseSecret }}
                  key: POSTGRES_PASSWORD
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
