apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gateway.className }}
  labels:
    {{- include "book-notes.commonLabels" . | nindent 4 }}
spec:
  controllerName: {{ .Values.gateway.controllerName }}
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: {{ .Values.gateway.envoyProxy.name }}
    namespace: {{ .Values.gateway.envoyProxy.namespace }}
