apiVersion: v1
kind: Service
metadata:
  name: book-notes-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "book-notes.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: postgres
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "book-notes.postgresSelectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: postgres
