apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace.yaml
  - base/configmap.yaml
  - base/schema-configmap.yaml
  - base/postgres-storage.yaml
  - base/postgres-service.yaml
  - base/postgres-statefulset.yaml
  - base/app-service.yaml
  - base/app-deployment.yaml
  - platform/envoy-proxy.yaml
  - platform/gateway-class.yaml
  - platform/gateway.yaml
  - platform/http-route.yaml
